Repository ayushi-ras/Hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#1 Create binary-search.cpp
  binary-search.cpp
Labels: good first issue, accepted

#4 Create Print Maze Paths.java
  Print Maze Paths.java
Labels: enhancement, good first issue, accepted

#5 Hangman.py
  Hangman.py
Labels: good first issue, accepted

#8 HeapSort.java
  HeapSort.java
Labels: accepted

#15 DSA: Finding the Missing Number
  Finding the Missing Number
Labels: hacktoberfest-accepted

#10 Added Kadane's Algorithm
  Kadane's Algorithm.cpp
Labels: good first issue, hacktoberfest-accepted

#19 Fixed issue #17
  BubbleSort.java
Labels: accepted, hacktoberfest-accepted

#24 Added figma
  figma/abc.css
  figma/abc.css.map
  figma/abc.html
  figma/abc.js
  figma/abc.scss
  figma/figma.html
  figma/image.png
  figma/style copy.css
  figma/style.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#27 Create quickSort.java
  Java/quickSort.java
Labels: hacktoberfest-accepted, hacktoberfest

#22 Create binaryTreeToBST.cpp
  C++/binaryTreeToBST.cpp
  Java/ArrayPythagorasTriplet.java
Labels: hacktoberfest-accepted, hacktoberfest

#28 Added binarySearch.py
  Python/binarySearch.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#30 Find middleelementlinkedlist
  C++/middleelementlinkedlist.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#31 Created Email_Slicer.py
  C++/Interesting_Pattern.cpp
  Python/Email_Slicer.py
Labels: hacktoberfest-accepted, hacktoberfest
